### ISSUE TITLE
s/zone/offset

### ISSUE THREAD

**Issue by icambron** [moment/moment#1779]
While we're deprecating and renaming things, maybe it's time to be consistent with our use of "zone" and "offset"? I'm kind of tired of explaining that `moment.zone()` isn't quite what it says on the tin, and I'm almost sure @mj1856 is too. What do you think, @ichernev?

**Comment by RumataEstor** [comment]
Now we have `moment().utcOffset() = - moment.tz.zone( <your local zone id>).offset(moment())`.

**Comment by almogdesign** [comment]
Hi everyone, 
I'm getting this error message but I'm not using moment zone I have 

moment().subtract(7, 'days')
moment().add(18, 'h')
moment().startOf('month')
moment().endOf('month')
             
Why am I getting the error message

**Comment by kashifshamaz21** [comment]
@almogdesign Can you add the error you are getting? Dont see any issue with those api calls.

**Comment by almogdesign** [comment]
@kashifshamaz21 here it is 
Deprecation warning: moment().zone is deprecated, use moment().utcOffset instead. https://github.com/moment/moment/issues/1779

function printMsg(msg) {
        if (moment.suppressDeprecationWarnings === false &&
                typeof console !== 'undefined' && console.warn) {
            console.warn('Deprecation warning: ' + msg);
        }
    }

**Comment by kashifshamaz21** [comment]
@almogdesign  I ran all 4 APIs you mentioned, on moment *2.9.0*, and didn't see any deprecation warning, as expected. 
The deprecation warning is shown only when `moment().zone()` is invoked.
Can you double check, you aren't invoking that call in your flow. A JSFiddle would help if you still face the issue without any zone() API calls being triggered.

**Comment by quickstep25** [comment]
Strangely enough, I am getting the same result on my local app, but I cannot reproduce in my [JSFiddle](http://jsfiddle.net/quickstep25/vck30kgL/). 

However, I am using Moment.Timezone but not making any calls to it directly, but other third party scripts I am using might be from just a couple lines of code.  
Using:
- Moment 2.9.0
- Timezone 0.3.0

Code is simple enough:

```
$(function () {

    var initDate = function (arrears) {
        return {
            startDate: moment().subtract(arrears, 'days').format('YYYY-MM-DD'),
            endDate: moment().subtract(arrears, 'days').format('YYYY-MM-DD')
        };
    };
    console.log(initDate(6));
});
/* JSFIDDLE is not producing the warnings as seen on local.  Expected Results: 
    - Deprecation warning: Accessing Moment through the global scope is deprecated, and will be removed in an upcoming release.
    - Deprecation warning: moment().zone is deprecated, use moment().utcOffset instead. https://github.com/moment/moment/issues/1779.
*/    
```
The warnings aren't causing any issues for me, just wanted to add to the investigation as I have not put energy into tracking the warnings down yet.

The other libraries I mentioned above as the possible culprits are:
- [require.js](http://requirejs.org/) - mentioning only because I couldn't put into fiddle
- [knockout.js](https://github.com/knockout/knockout) - mentioning because I am creating a custom component and couldn't quickly get it in a fiddle
- [daterangepicker.js](https://github.com/dangrossman/bootstrap-daterangepicker)

So I highly, I suspect daterangepicker is using the timezone in some fashion....

Not sure if that helps but in @almogdesign case, perhaps another library is causing the warnings to popup at the first usage of moment.

**Comment by almogdesign** [comment]
Yes I'm also using daterangepicker.js which I think is casing the issue

**Comment by quickstep25** [comment]
I just noticed this evening what the problem which you have already pointed out.   :)

I updated daterangepicker to the new release. 1.3.18 which has those fixes contained within, and I no longer have the warnings from moment.js

**Comment by almogdesign** [comment]
Thanks

**Comment by samholmes** [comment]
>Deprecation warning: moment().zone is deprecated, use moment().utcOffset instead. https://github.com/moment/moment/issues/1779

This is the message I get when running my app. I don't use the zone method at all in my app, so why am I getting a warning about it?

**Comment by mj1856** [comment]
@samholmes - hard to say without seeing an example.  Perhaps you have some other dependency that uses it?  If you can post a jsFiddle or similar that reproduces the message, I'd be happy to investigate.  Otherwise, dive in to your browser's debugging tools and check the stack trace to see what's making the call to that function.

**Comment by samholmes** [comment]
```sh
$ npm list moment
SECRET@0.0.0 /Users/holmes/Code/SECRET/app
├─┬ cron@1.0.6
│ └─┬ moment-timezone@0.2.4
│   └── moment@2.9.0 
└── moment@2.9.0 
```

Is this a 2.9.0 problem?

**Comment by mj1856** [comment]
@samholmes  - This looks like the same as moment/moment-timezone/issues/228.  I see you're using moment-timezone 0.2.4.   I can also see that [cron 1.0.6](https://github.com/ncb000gt/node-cron/blob/v1.0.6/package.json) took a hard dependency on moment-timezone version 0.2.4, but [in the current version](https://github.com/ncb000gt/node-cron/blob/master/package.json) it asks for `"~0.3.0"` - which I understand to mean >= 0.3.0 and < 1.0.0.

Therefore, updating to the latest cron and moment versions should fix the issue.

**Comment by robertdumitrescu** [comment]
I changed the the zone to utcOffset in my implementation but I still get the deprecation error. What can I do to avoid that. I made sure that aren't any .zone() calls in my implementatioin.

**Comment by mj1856** [comment]
@robertdumitrescu search your code.  Or put it somewhere we can search and give a URL.  Not sure what else I could suggest.
