### ISSUE TITLE
French locale is used by default

### ISSUE THREAD

**Issue by nastya-kostyukova** [moment/moment#3977]
When I try to create new moment date without setting locale, date has french locale.

Environment  Node.JS v.6.9.1 on Ubuntu 16.0.4

Example of usage:
console.log(koa.request.body.startDate); //return _2017-05-25_
console.log(moment(koa.request.body.startDate, 'YYYY-MM-DD').locale()); //return **fr**

This bug is replicated locally and on production, which has the same environment, but different timezone.

---
console.log( (new Date()).toString())
console.log((new Date()).toLocaleString())
console.log( (new Date()).getTimezoneOffset())
console.log( navigator.userAgent)
console.log(moment.version)
 
Result:
Thu May 25 2017 10:56:52 GMT+0300 (MSK)
5/25/2017, 10:56:52 AM
-180
2.10.6

**Comment by bryanhiggins** [comment]
I'm seeing the same issue.

Explicitly setting locale worked around it
`require('moment').locale('en');`

**Comment by icambron** [comment]
That's certainly odd. 2.10.6 is pretty old though. If you upgrade to the latest, does it still happen?

You can set Moment's default locale with

```js
moment.locale('en');
```

It should be on 'en' by default but if something hidden is setting it, that's the workaround.

**Comment by bryanhiggins** [comment]
I'm actually on 2.18.1.

I'm also using Ubuntu as the original reporter is. The system locale is set to US English. 

Above workaround does fix it.

**Comment by nastya-kostyukova** [comment]
I have updated version and result is the same, but the workaround helps.

**Comment by jayjanssen** [comment]
I see the same issue -- I was installing '^2.15.1', and in the last week or so got French suddenly.  I had inconsistent behaviors across docker image builds, so I suspect there is a bad version in the NPM mirrors somewhere that gets pulled sometimes.  Just a guess.

Moving to '^2.18.1' seems to have addressed it for me for now. YMMV

**Comment by 0xc00010ff** [comment]
I'm on 2.18.1, seeing the same thing suddenly in production. Haven't changed any code, just deployed a build that triggered an npm install.

**Comment by ajsouza** [comment]
Also seeing the same issue +1

**Comment by roymap** [comment]
+1

**Comment by icambron** [comment]
Enough of you have reported this that I'm convinced we need to do something to fix it, but I'm not in a position to help, partially because it seems to be Linux-specific and I don't currently have a dev environment set up there. So...help wanted.

**Comment by nikshepsvn** [comment]
would love to give this a shot? can someone give me an idea of how to start off?

**Comment by icambron** [comment]
This might not be a great starter project, TBH. But if you want to try it, you'd need to reproduce it and then do some debugging of Moment's locale methods to see what's happening. I don't know what the problem is, so I'm not quite sure how to point you the right way

**Comment by Debdutto** [comment]
@icambron Has anyone finished this? Or has it been fixed in a later release? I would like to give it a shot. I'm on Mac but I can probably set up a Dev Ubuntu Environment using Docker and try this out.

**Comment by icambron** [comment]
@Debdutto As far as I know, this is still an open issue. So yeah, go for it

**Comment by Debdutto** [comment]
@icambron @nastya-kostyukova 

I have not been able to reproduce the bug. I am running Ubuntu 16.0.4 in a docker container.

```javascript
console.log(moment("2017-05-25", 'YYYY-MM-DD').locale());
console.log((new Date()).toString())
console.log((new Date()).toLocaleString())
console.log((new Date()).getTimezoneOffset())
console.log(moment.version)
```
The code above gives the output:

```
en
Fri Dec 08 2017 17:32:11 GMT+0000 (UTC)
12/8/2017, 5:32:11 PM
0
2.10.6
```

```node -v``` gives ```v6.9.1```
```npm -v``` gives ```3.10.8```

Ubuntu version is ```16.0.4```

Is anybody still having this issue? Maybe we can figure out what precise scenario causes this.

**Comment by marwahaha** [comment]
Are folks still seeing this on 2.19.4 ? 

This one might be related -  https://github.com/moment/moment/issues/4116

**Comment by marwahaha** [comment]
@nastya-kostyukova @bryanhiggins @jayjanssen @0xc00010ff @ajsouza @roymap  - has anyone been able to reproduce this in 2.19.x or 2.20.x ?

**Comment by marwahaha** [comment]
I'm going to close this - but please re-open if it's still a problem.
